# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duex < Formula
  desc "Duex is a Go-based terminal utility for visualizing and analyzing disk usage, featuring interactive navigation, accurate sizing, and real-time feedback."
  homepage "https://github.com/evilmarty/duex"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evilmarty/duex/releases/download/v1.2.0/duex-1.2.0-darwin_amd64"
      sha256 "7dd4df3ec12299073d6624d38bb5a7ba162643f8059157894926c73acb417016"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evilmarty/duex/releases/download/v1.2.0/duex-1.2.0-darwin_arm64"
      sha256 "1464b9225b338bc248431ef4bb28a69d1174d0c94be783b03c6e5d4b75016fc1"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/duex/releases/download/v1.2.0/duex-1.2.0-linux_amd64"
      sha256 "57af42a9adbf5a6323d624cb635f40532dd4030d92125a4413c10e7a98454cb7"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/duex/releases/download/v1.2.0/duex-1.2.0-linux_armv6"
      sha256 "c8081153aa390f025ca0f390ae0bc5e601a01b1f2707cae63b973df9bdeca9d6"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/duex/releases/download/v1.2.0/duex-1.2.0-linux_arm64"
      sha256 "9c2972541f087b1ad781ead3a521c93553bc68eae154288440908f83f8afd538"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  head do
    url "https://github.com/evilmarty/duex.git", branch: "main"
    depends_on "go" => :build
  end

  test do
    version_output = shell_output(bin/"duex --version")
    assert_match "duex version #{version}", version_output
  end
end
