# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duex < Formula
  desc "Duex is a Go-based terminal utility for visualizing and analyzing disk usage, featuring interactive navigation, accurate sizing, and real-time feedback."
  homepage "https://github.com/evilmarty/duex"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evilmarty/duex/releases/download/v1.0.0/duex-1.0.0-darwin_amd64"
      sha256 "843440a4341cbcd79b3d4479528f61ab1776418202cb10ab3cc181391f46e531"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evilmarty/duex/releases/download/v1.0.0/duex-1.0.0-darwin_arm64"
      sha256 "909e2678aeb25f2e3718875c63c80a48a98b6928bda2dd78409b3290bc837b10"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/duex/releases/download/v1.0.0/duex-1.0.0-linux_amd64"
      sha256 "6f9b81765aaaf49d45e9655093418d2be365567da7fe23ec51806b363aa121dd"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/duex/releases/download/v1.0.0/duex-1.0.0-linux_armv6"
      sha256 "bfa239e6b5391cc4a0b9da208f4c33b3cad60728356a6e4726ebc1865db0cc61"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/duex/releases/download/v1.0.0/duex-1.0.0-linux_arm64"
      sha256 "214256f619f57ff33563b0ae1aa5ef39f6ed4b2e6446d4c27495662c99e0311e"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  head do
    url "https://github.com/evilmarty/duex.git", branch: "main"
    depends_on "go" => :build
  end

  test do
    version_output = shell_output(bin/"duex --version")
    assert_match "duex version #{version}", version_output
  end
end
