# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duex < Formula
  desc "Duex is a Go-based terminal utility for visualizing and analyzing disk usage, featuring interactive navigation, accurate sizing, and real-time feedback."
  homepage "https://github.com/evilmarty/duex"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evilmarty/duex/releases/download/v1.1.0/duex-1.1.0-darwin_amd64"
      sha256 "90e3b2c0bdde9308cf872010764c9c1037b23b14588acaa647307dabf079ec86"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evilmarty/duex/releases/download/v1.1.0/duex-1.1.0-darwin_arm64"
      sha256 "50d65bb08de7e55f9f4376cfdb1eac627fd2718a6656be222cd4aea5693100f4"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/duex/releases/download/v1.1.0/duex-1.1.0-linux_amd64"
      sha256 "a2901d24369a3b04e666d714035f089342cd2e73d578e16bf67e6197205e4572"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/duex/releases/download/v1.1.0/duex-1.1.0-linux_armv6"
      sha256 "1d8953d3f2a9db2768ba36cabf484c91ac8bcab58d82b3a2e8d4f6859a1130fb"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/duex/releases/download/v1.1.0/duex-1.1.0-linux_arm64"
      sha256 "e7b44586ac1d0ce3b4d181e3371c5a692ad3810fdae9f1b875d8723d4575a8d4"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  head do
    url "https://github.com/evilmarty/duex.git", branch: "main"
    depends_on "go" => :build
  end

  test do
    version_output = shell_output(bin/"duex --version")
    assert_match "duex version #{version}", version_output
  end
end
